<a href="https://colab.research.google.com/github/evegarcianz/Repository/blob/main/COMP527CA1_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd
import numpy as np
import random


Functions of X and labels 

In [104]:
def X_and_labels_train(dataframe,first_class,second_class):
  data_array=np.array(dataframe)
  rng = np.random.default_rng(seed=10)
  rng.shuffle(data_array)
  class_mask=np.logical_or(data_array[:,4]==first_class, data_array[:,4]==second_class)
  array_class1_class2=data_array[class_mask,:]
  array_class1_class2=np.where(array_class1_class2==first_class,1,array_class1_class2)
  array_class1_class2=np.where(array_class1_class2==second_class,-1,array_class1_class2)
  X_train_class1_class2=array_class1_class2[:,0:-1]
  labels_train_class1_class2=array_class1_class2[:,-1]
  return X_train_class1_class2, labels_train_class1_class2

In [84]:
def X_and_labels_test(dataframe,first_class,second_class):
  data_array=np.array(dataframe)
  class_mask=np.logical_or(data_array[:,4]==first_class, data_array[:,4]==second_class)
  array_class1_class2=data_array[class_mask,:]
  array_class1_class2=np.where(array_class1_class2==
  first_class,1,array_class1_class2)
  array_class1_class2=np.where(array_class1_class2==second_class,-1,array_class1_class2)
  X_train_class1_class2=array_class1_class2[:,0:-1]
  labels_train_class1_class2=array_class1_class2[:,-1]
  return X_train_class1_class2, labels_train_class1_class2

### Training the algorithm

Perceptron fit

In [85]:
def perceptron_1v1_fit(traindf,testdf,classA,classB):
  X_train_class1_class2, labels_train_class1_class2=X_and_labels_train(traindf,classA,classB)
  X_test_class1_class2, labels_test_class1_class2=X_and_labels_test(testdf,classA,classB)

  W=np.zeros(X_train_class1_class2.shape[1])
  b=0
  miu=0.0001
  loss_function=0

  for iter in range(1,20):
    for (x,y) in zip(X_train_class1_class2,labels_train_class1_class2):
      #print('------------')
      #print(f'iter number {iter}')
      #print(f'This is x={x}')
      #print(f'This is y= {y}')
      #print(f'This is current W= {W}')
      #print(f'This is current b= {b}')
      a=np.dot(np.transpose(W),x)+b
      #print(f'This is a= {a}')
      #print(f'This is the loss function -y * a = {-y*a}')
      loss_function=loss_function+(-y*a)
      #print(f'This is summatory of  loss function {loss_function}')
      if y*a <= 0:
        W=W+(miu*y*x)
        b=b+(miu*y)
      #print('After y*a conditional')
      #print(f'This is updated W= {W}')
      #print(f'This is updated b= {b}')


      
  return W,b,loss_function, X_test_class1_class2, labels_test_class1_class2


### Predict function

In [86]:
def predict(X_test_class1_class2,W,b):
  predicted=np.array([])
  for x in X_test_class1_class2:
    pred=np.dot(np.transpose(W),x)+b
    if pred > 0:
      predicted=np.append(predicted,1)
    else:
      predicted=np.append(predicted,-1)
  return predicted

Calculating accuracy

In [87]:
def scores(y_pred,y_true):
  ConfusionMatrix = np.zeros((2,2), int)
  for (pred,lab) in zip(predicted,labels_test_class1_class2):
    if pred==1:
      if pred==lab:
        ConfusionMatrix[0,0]+=1
      if pred!=lab:
        ConfusionMatrix[0,1]+=1
    if pred==-1:
      if pred==lab:
        ConfusionMatrix[1,1]+=1
      if pred!=lab:
        ConfusionMatrix[0,1]+=1
  
  tp=ConfusionMatrix[0,0]
  fp=ConfusionMatrix[0,1]
  fn=ConfusionMatrix[1,0]
  tn=ConfusionMatrix[1,1]
  accuracy= (tp+tn)/(tp+fp+fn+tn)
  precision= tp/(tp+fp)
  recall= tp/(tp+fn)
  f_score=(2*precision*recall)/(precision+recall)

  

  return f'Accuracy= {accuracy}, Precision= {precision}, Recall= {recall}, F-Score= {f_score}'
 

### Read Train and Test Data

In [88]:
df_train = pd.read_csv('/content/train.data', header=None)


In [89]:
df_test = pd.read_csv('/content/test.data', header=None)

For Class 1 and 2

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [90]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-1','class-2')

Printing W, b and loss function

In [91]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [8.000000000000016e-05 0.00051 -0.0006300000000000001 -0.00029]
b is 0.0001
The loss function is -1.800656999999999


Getting prediction

In [92]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [93]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 1.0, Precision= 1.0, Recall= 1.0, F-Score= 1.0'

For Class 1 and 3

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [94]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-1','class-3')

Printing W, b and loss function

In [95]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [0.00019000000000000012 0.0005300000000000001 -0.0008900000000000002
 -0.00049]
b is 0.0001
The loss function is -3.40047299999999


Getting prediction

In [96]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [97]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 1.0, Precision= 1.0, Recall= 1.0, F-Score= 1.0'

For Class 2 and 3

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [98]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-2','class-3')

Printing W, b and loss function

In [99]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [0.004370000000000008 0.0025199999999999997 -0.006019999999999997
 -0.004420000000000006]
b is 0.0017000000000000006
The loss function is -4.153765000000003


Getting prediction

In [100]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [101]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 1.0, Precision= 1.0, Recall= 1.0, F-Score= 1.0'