<a href="https://colab.research.google.com/github/evegarcianz/Repository/blob/main/COMP527CA1_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np



Functions of X and labels 

In [32]:
def X_and_labels_train(dataframe,first_class,second_class):
  data_array=np.array(dataframe)
  np.random.shuffle(data_array)
  class_mask=np.logical_or(data_array[:,4]==first_class, data_array[:,4]==second_class)
  array_class1_class2=data_array[class_mask,:]
  array_class1_class2=np.where(array_class1_class2==first_class,1,array_class1_class2)
  array_class1_class2=np.where(array_class1_class2==second_class,-1,array_class1_class2)
  X_train_class1_class2=array_class1_class2[:,0:-1]
  labels_train_class1_class2=array_class1_class2[:,-1]
  return X_train_class1_class2, labels_train_class1_class2

In [33]:
def X_and_labels_test(dataframe,first_class,second_class):
  data_array=np.array(dataframe)
  class_mask=np.logical_or(data_array[:,4]==first_class, data_array[:,4]==second_class)
  array_class1_class2=data_array[class_mask,:]
  array_class1_class2=np.where(array_class1_class2==
  first_class,1,array_class1_class2)
  array_class1_class2=np.where(array_class1_class2==second_class,-1,array_class1_class2)
  X_train_class1_class2=array_class1_class2[:,0:-1]
  labels_train_class1_class2=array_class1_class2[:,-1]
  return X_train_class1_class2, labels_train_class1_class2

### Training the algorithm

Perceptron fit

In [34]:
def perceptron_1v1_fit(traindf,testdf,classA,classB):
  X_train_class1_class2, labels_train_class1_class2=X_and_labels_train(traindf,classA,classB)
  X_test_class1_class2, labels_test_class1_class2=X_and_labels_test(testdf,classA,classB)

  W=np.zeros(X_train_class1_class2.shape[1])
  b=0
  miu=0.0001
  loss_function=0

  for iter in range(1,20):
    for (x,y) in zip(X_train_class1_class2,labels_train_class1_class2):
      #print('------------')
      #print(f'iter number {iter}')
      #print(f'This is x={x}')
      #print(f'This is y= {y}')
      #print(f'This is current W= {W}')
      #print(f'This is current b= {b}')
      a=np.dot(np.transpose(W),x)+b
      #print(f'This is a= {a}')
      #print(f'This is the loss function -y * a = {-y*a}')
      loss_function=loss_function+(-y*a)
      #print(f'This is summatory of  loss function {loss_function}')
      if y*a <= 0:
        W=W+(miu*y*x)
        b=b+(miu*y)
      #print('After y*a conditional')
      #print(f'This is updated W= {W}')
      #print(f'This is updated b= {b}')


      
  return W,b,loss_function, X_test_class1_class2, labels_test_class1_class2


### Predict function

In [35]:
def predict(X_test_class1_class2,W,b):
  predicted=np.array([])
  for x in X_test_class1_class2:
    pred=np.dot(np.transpose(W),x)+b
    if pred > 0:
      predicted=np.append(predicted,1)
    else:
      predicted=np.append(predicted,-1)
  return predicted

Calculating accuracy

In [36]:
def scores(y_pred,y_true):
  ConfusionMatrix = np.zeros((2,2), int)
  for (pred,lab) in zip(predicted,labels_test_class1_class2):
    if pred==1:
      if pred==lab:
        ConfusionMatrix[0,0]+=1
      if pred!=lab:
        ConfusionMatrix[0,1]+=1
    if pred==-1:
      if pred==lab:
        ConfusionMatrix[1,1]+=1
      if pred!=lab:
        ConfusionMatrix[0,1]+=1
  
  tp=ConfusionMatrix[0,0]
  fp=ConfusionMatrix[0,1]
  fn=ConfusionMatrix[1,0]
  tn=ConfusionMatrix[1,1]
  accuracy= (tp+tn)/(tp+fp+fn+tn)
  precision= tp/(tp+fp)
  recall= tp/(tp+fn)
  f_score=(2*precision*recall)/(precision+recall)

  

  return f'Accuracy= {accuracy}, Precision= {precision}, Recall= {recall}, F-Score= {f_score}'
 

### Read Train and Test Data

In [37]:
df_train = pd.read_csv('/content/train.data', header=None)


In [38]:
df_test = pd.read_csv('/content/test.data', header=None)

For Class 1 and 2

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [39]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-1','class-2')

Printing W, b and loss function

In [40]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [0.00020000000000000025 0.0005 -0.0007000000000000001 -0.00027]
b is 0.0001
The loss function is -1.8659309999999893


Getting prediction

In [41]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [42]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 1.0, Precision= 1.0, Recall= 1.0, F-Score= 1.0'

For Class 1 and 3

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [43]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-1','class-3')

Printing W, b and loss function

In [44]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [0.0001499999999999999 0.00043 -0.0007200000000000002 -0.00035]
b is 0.0001
The loss function is -2.6922819999999974


Getting prediction

In [45]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [46]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 1.0, Precision= 1.0, Recall= 1.0, F-Score= 1.0'

For Class 2 and 3

Fitting: Calculating weights, bias, loss function, X_test and labels_test

In [47]:
W,b,loss_function, X_test_class1_class2, labels_test_class1_class2=perceptron_1v1_fit(df_train,df_test,'class-2','class-3')

Printing W, b and loss function

In [48]:
print(f'Weights are {W}')
print(f'b is {b}')
print(f'The loss function is {loss_function}')

Weights are [0.0026200000000000017 0.003569999999999995 -0.005760000000000009
 -0.0035600000000000093]
b is 0.0024
The loss function is -3.2356360000000115


Getting prediction

In [49]:
predicted=predict(X_test_class1_class2,W,b)
predicted

array([-1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

Getting Accuracy

In [50]:
scores(predicted,labels_test_class1_class2)

'Accuracy= 0.6, Precision= 0.2, Recall= 1.0, F-Score= 0.33333333333333337'